name: gestongo-dev
services:
  api:
    build: ./backend
    environment: [NODE_ENV=development, PORT=8000]
    expose: ["8000"]
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  web:
    build: ./frontend
    depends_on: [api]
    ports: ["8080:80"]
    environment:
      - REACT_APP_API_BASE=/api

  nginx:
    image: nginx:alpine
    ports: ["3000:80"]
    depends_on: [web, api]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
