name: E2E on published images

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: read

env:
  REGISTRY: ghcr.io
  IMAGE_FRONTEND: ${{ github.repository }}/frontend
  IMAGE_BACKEND:  ${{ github.repository }}/backend
  TAG: latest

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create compose.override for E2E
        run: |
          cat > compose.override.yaml <<EOF
          services:
            api:
              image: ${REGISTRY}/${IMAGE_BACKEND}:${TAG}
            web:
              image: ${REGISTRY}/${IMAGE_FRONTEND}:${TAG}
            e2e:
              build: ./e2e
              environment:
                - BASE_URL=http://web
          EOF

      - name: Run E2E against images
        run: |
          docker compose -f compose.e2e.yaml -f compose.override.yaml up --abort-on-container-exit --exit-code-from e2e
